// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: inner/v1/app.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppExternalInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AppExternalInfoRequest) Reset() {
	*x = AppExternalInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_v1_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppExternalInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppExternalInfoRequest) ProtoMessage() {}

func (x *AppExternalInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inner_v1_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppExternalInfoRequest.ProtoReflect.Descriptor instead.
func (*AppExternalInfoRequest) Descriptor() ([]byte, []int) {
	return file_inner_v1_app_proto_rawDescGZIP(), []int{0}
}

type AttributeSchemaItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AttributeSchemaItem) Reset() {
	*x = AttributeSchemaItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_v1_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeSchemaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeSchemaItem) ProtoMessage() {}

func (x *AttributeSchemaItem) ProtoReflect() protoreflect.Message {
	mi := &file_inner_v1_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeSchemaItem.ProtoReflect.Descriptor instead.
func (*AttributeSchemaItem) Descriptor() ([]byte, []int) {
	return file_inner_v1_app_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeSchemaItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AttributeSchemaItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AttributeSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[string]*AttributeSchemaItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AttributeSchema) Reset() {
	*x = AttributeSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_v1_app_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeSchema) ProtoMessage() {}

func (x *AttributeSchema) ProtoReflect() protoreflect.Message {
	mi := &file_inner_v1_app_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeSchema.ProtoReflect.Descriptor instead.
func (*AttributeSchema) Descriptor() ([]byte, []int) {
	return file_inner_v1_app_proto_rawDescGZIP(), []int{2}
}

func (x *AttributeSchema) GetItems() map[string]*AttributeSchemaItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProcessorExternalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AttributeSchema *AttributeSchema `protobuf:"bytes,2,opt,name=attributeSchema,proto3" json:"attributeSchema,omitempty"`
}

func (x *ProcessorExternalInfo) Reset() {
	*x = ProcessorExternalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_v1_app_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessorExternalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorExternalInfo) ProtoMessage() {}

func (x *ProcessorExternalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inner_v1_app_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorExternalInfo.ProtoReflect.Descriptor instead.
func (*ProcessorExternalInfo) Descriptor() ([]byte, []int) {
	return file_inner_v1_app_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessorExternalInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessorExternalInfo) GetAttributeSchema() *AttributeSchema {
	if x != nil {
		return x.AttributeSchema
	}
	return nil
}

type AppInfoExternalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processors []*ProcessorExternalInfo `protobuf:"bytes,1,rep,name=processors,proto3" json:"processors,omitempty"`
}

func (x *AppInfoExternalResponse) Reset() {
	*x = AppInfoExternalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_v1_app_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInfoExternalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfoExternalResponse) ProtoMessage() {}

func (x *AppInfoExternalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inner_v1_app_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfoExternalResponse.ProtoReflect.Descriptor instead.
func (*AppInfoExternalResponse) Descriptor() ([]byte, []int) {
	return file_inner_v1_app_proto_rawDescGZIP(), []int{4}
}

func (x *AppInfoExternalResponse) GetProcessors() []*ProcessorExternalInfo {
	if x != nil {
		return x.Processors
	}
	return nil
}

var File_inner_v1_app_proto protoreflect.FileDescriptor

var file_inner_v1_app_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x67, 0x72, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x46, 0x6c, 0x6f,
	0x77, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x18, 0x0a, 0x16, 0x41, 0x70,
	0x70, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x13, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xbe, 0x01, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x46, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x67, 0x72, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x46, 0x6c,
	0x6f, 0x77, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x63, 0x0a,
	0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3f, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x67,
	0x72, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x7c, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x4f, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x72, 0x65, 0x62, 0x62,
	0x6c, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52,
	0x0f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x22, 0x66, 0x0a, 0x17, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x67, 0x72, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x2e, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x73, 0x32, 0x77, 0x0a, 0x0b, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x41, 0x70, 0x70, 0x12, 0x68, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2c, 0x2e, 0x67, 0x72, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x46, 0x6c, 0x6f, 0x77,
	0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2d, 0x2e, 0x67, 0x72, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x2e, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x72, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x67, 0x6f, 0x2d, 0x6d, 0x6f, 0x6e, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inner_v1_app_proto_rawDescOnce sync.Once
	file_inner_v1_app_proto_rawDescData = file_inner_v1_app_proto_rawDesc
)

func file_inner_v1_app_proto_rawDescGZIP() []byte {
	file_inner_v1_app_proto_rawDescOnce.Do(func() {
		file_inner_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_inner_v1_app_proto_rawDescData)
	})
	return file_inner_v1_app_proto_rawDescData
}

var file_inner_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inner_v1_app_proto_goTypes = []interface{}{
	(*AppExternalInfoRequest)(nil),  // 0: grebbleFlow.inner.v1.AppExternalInfoRequest
	(*AttributeSchemaItem)(nil),     // 1: grebbleFlow.inner.v1.AttributeSchemaItem
	(*AttributeSchema)(nil),         // 2: grebbleFlow.inner.v1.AttributeSchema
	(*ProcessorExternalInfo)(nil),   // 3: grebbleFlow.inner.v1.ProcessorExternalInfo
	(*AppInfoExternalResponse)(nil), // 4: grebbleFlow.inner.v1.AppInfoExternalResponse
	nil,                             // 5: grebbleFlow.inner.v1.AttributeSchema.ItemsEntry
}
var file_inner_v1_app_proto_depIdxs = []int32{
	5, // 0: grebbleFlow.inner.v1.AttributeSchema.items:type_name -> grebbleFlow.inner.v1.AttributeSchema.ItemsEntry
	2, // 1: grebbleFlow.inner.v1.ProcessorExternalInfo.attributeSchema:type_name -> grebbleFlow.inner.v1.AttributeSchema
	3, // 2: grebbleFlow.inner.v1.AppInfoExternalResponse.processors:type_name -> grebbleFlow.inner.v1.ProcessorExternalInfo
	1, // 3: grebbleFlow.inner.v1.AttributeSchema.ItemsEntry.value:type_name -> grebbleFlow.inner.v1.AttributeSchemaItem
	0, // 4: grebbleFlow.inner.v1.ExternalApp.AppInfo:input_type -> grebbleFlow.inner.v1.AppExternalInfoRequest
	4, // 5: grebbleFlow.inner.v1.ExternalApp.AppInfo:output_type -> grebbleFlow.inner.v1.AppInfoExternalResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inner_v1_app_proto_init() }
func file_inner_v1_app_proto_init() {
	if File_inner_v1_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inner_v1_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppExternalInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_v1_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeSchemaItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_v1_app_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_v1_app_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessorExternalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_v1_app_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInfoExternalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inner_v1_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inner_v1_app_proto_goTypes,
		DependencyIndexes: file_inner_v1_app_proto_depIdxs,
		MessageInfos:      file_inner_v1_app_proto_msgTypes,
	}.Build()
	File_inner_v1_app_proto = out.File
	file_inner_v1_app_proto_rawDesc = nil
	file_inner_v1_app_proto_goTypes = nil
	file_inner_v1_app_proto_depIdxs = nil
}
